# -*- coding: utf-8 -*-
"""Final_Script_Alignment_isa (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mtqpZ7vpU8A24TiwH12lFybOsCJdn3Y

## 🔧 Step 1 — Install All Dependencies
> Run this cell **once** and then **restart the runtime** when prompted.
"""

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTANT: After this cell finishes, click:
#   Runtime → Restart runtime
# Then run from Step 2 onwards. Do NOT re-run this cell.
# ─────────────────────────────────────────────────────────────────────────────

import subprocess, sys

def pip(*args):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + list(args))

def uninstall(*pkgs):
    subprocess.check_call(
        [sys.executable, "-m", "pip", "uninstall", "-y"] + list(pkgs),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )

import torch
print(f"Detected torch {torch.__version__}")

# ── 1. Remove torchvision (torch 2.8 nms conflict, not needed for audio) ─────
print("[1/7] Removing torchvision...")
uninstall("torchvision")

# ── 2. Force-reinstall transformers ──────────────────────────────────────────
print("[2/7] Reinstalling transformers...")
uninstall("transformers")
pip("--force-reinstall", "--no-cache-dir", "transformers")

# ── 3. bitsandbytes + accelerate ─────────────────────────────────────────────
print("[3/7] bitsandbytes, accelerate...")
pip("bitsandbytes>=0.41.0", "accelerate>=0.26.0")

# ── 4. audio / video libraries ───────────────────────────────────────────────
print("[4/7] moviepy, librosa, soundfile...")
pip("moviepy", "librosa", "soundfile")

# ── 5. WhisperX and deps ─────────────────────────────────────────────────────
print("[5/7] faster-whisper, whisperx...")
pip("faster-whisper")
pip("whisperx")

# ── 6. remaining deps ────────────────────────────────────────────────────────
print("[6/7] omegaconf, pandas, openpyxl...")
pip("omegaconf", "pandas", "openpyxl")

# ── 7. Force NumPy + numba LAST — redefine pip here in case kernel restarted ─
print("[7/7] Pinning numpy<2.0 and numba (LAST step)...")
import subprocess, sys
_pip = lambda *a: subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + list(a))
_pip("--force-reinstall", "numpy<2.0")
_pip("numba<0.60")

print()
print("✅ All dependencies installed!")
print("👉  Runtime → Restart runtime  → then continue from Step 2.")

"""## 📦 Step 2 — Imports
> Run after restarting the runtime.
"""

import torch
import torchaudio
import numpy as np
import os
import gc
import re
import json
import difflib
import pandas as pd
import librosa
import soundfile as sf

from transformers import AutoProcessor, SeamlessM4Tv2Model
from moviepy.editor import VideoFileClip
from IPython.display import Audio, HTML, display
from google.colab import files, drive

# ── Patch torch.load for WhisperX / omegaconf compatibility ──────────────────
import torch.serialization
try:
    from omegaconf.listconfig import ListConfig
    from omegaconf.dictconfig import DictConfig
    torch.serialization.add_safe_globals([ListConfig, DictConfig])
except ImportError:
    pass

_orig_torch_load = torch.load
torch.load = lambda *a, **kw: _orig_torch_load(*a, **{**kw, "weights_only": False})

# ── Device ────────────────────────────────────────────────────────────────────
device = "cuda" if torch.cuda.is_available() else "cpu"
compute_type = "float16" if device == "cuda" else "float32"

if device == "cuda":
    print(f"✅ GPU: {torch.cuda.get_device_name(0)}")
    print(f"   Total VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("⚠️  No GPU detected — transcription will be very slow on CPU.")

"""## 🤖 Step 3 — Load Seamless M4T v2 Model

The model is ~10 GB. It will be downloaded from HuggingFace once and cached in
your Google Drive under a folder called .

**If you already downloaded it before**, this cell will load it from Drive
without re-downloading.

"""

# ── Mount Drive ───────────────────────────────────────────────────────────────
print("Mounting Google Drive...")
drive.mount("/content/drive", force_remount=False)

# ── Locate or create model folder ─────────────────────────────────────────────
MYDRIVE = "/content/drive/MyDrive"
model_dir = None

for item in os.listdir(MYDRIVE):
    if "seamless" in item.lower():
        candidate = os.path.join(MYDRIVE, item)
        if os.path.isdir(candidate):
            model_dir = candidate
            print(f"Found existing model folder: {model_dir}")
            break

if model_dir is None:
    model_dir = os.path.join(MYDRIVE, "seamless-m4t-v2-large")
    os.makedirs(model_dir, exist_ok=True)
    print(f"Created new model folder: {model_dir}")

# ── Load or download ──────────────────────────────────────────────────────────
config_path = os.path.join(model_dir, "config.json")

if os.path.exists(config_path):
    print("Loading model from Google Drive (no download needed)...")
    local_files_only = True
    model_id = model_dir
else:
    print("Model not found locally — downloading from HuggingFace (~10 GB)...")
    local_files_only = False
    model_id = "facebook/seamless-m4t-v2-large"

processor = AutoProcessor.from_pretrained(model_id, local_files_only=local_files_only)

model = SeamlessM4Tv2Model.from_pretrained(
    model_id,
    load_in_8bit=True,       # ~50% VRAM savings
    device_map="auto",
    local_files_only=local_files_only,
)

if not os.path.exists(config_path):
    print("Saving model to Google Drive for future use...")
    processor.save_pretrained(model_dir)
    model.save_pretrained(model_dir)
    print(f"✅ Saved to: {model_dir}")

print("✅ Model ready!")
if torch.cuda.is_available():
    used = torch.cuda.memory_allocated(0) / 1e9
    total = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"   GPU VRAM used: {used:.1f} / {total:.1f} GB")

"""## 📹 Step 4 — Upload Your Audio"""

print("Please upload your audio file (wav, mp3, m4a, flac, ogg...)")
uploaded = files.upload()
audio_filename = list(uploaded.keys())[0]
print(f"✅ Uploaded: {audio_filename}")
print("Loading audio...")

# Convert to WAV if needed (librosa handles most formats)
audio_array, sample_rate = librosa.load(audio_filename, sr=16000)

# Optionally save a clean WAV copy for WhisperX compatibility
wav_path = "/content/extracted_audio.wav"
import soundfile as sf
sf.write(wav_path, audio_array, 16000)
audio_filename = wav_path  # keep using this variable name downstream

print(f"✅ Audio loaded from uploaded file")
duration = len(audio_array) / sample_rate
print(f"   Duration : {duration:.1f}s  ({duration/60:.1f} min)")
print(f"   Sample rate: {sample_rate} Hz")

display(Audio(audio_filename, autoplay=False))

"""## ✍️ Step 6 — Transcribe with SeamlessM4T (Chunked)

Audio is processed in **20-second chunks** to avoid running out of GPU memory.
Egyptian Arabic target language code:

"""

def transcribe_with_chunking(audio_array, chunk_length_seconds=20, overlap_seconds=1):
    """Transcribe long audio by splitting into overlapping chunks."""
    sr = 16000
    chunk_size   = chunk_length_seconds * sr
    overlap_size = overlap_seconds      * sr
    step         = chunk_size - overlap_size

    transcriptions = []
    starts = list(range(0, len(audio_array), step))
    total  = len(starts)

    print(f"Processing {total} chunk(s) of ~{chunk_length_seconds}s each...\n")

    for idx, i in enumerate(starts, 1):
        chunk = audio_array[i : i + chunk_size]

        if len(chunk) < sr * 0.5:   # skip < 0.5 s
            continue

        print(f"  Chunk {idx}/{total}  ({len(chunk)/sr:.1f}s)...", end=" ", flush=True)

        try:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()

            inputs = processor(
                audios=chunk,
                sampling_rate=sr,
                return_tensors="pt",
            ).to(device)

            with torch.no_grad():
                output_tokens = model.generate(
                    **inputs,
                    tgt_lang="eng",
                    generate_speech=False,
                    max_new_tokens=256,
                )

            text = processor.decode(
                output_tokens[0].tolist()[0],
                skip_special_tokens=True,
            )
            transcriptions.append(text)
            print("✓")

            del inputs, output_tokens
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        except Exception as e:
            print(f"✗ Error: {e}")

    return " ".join(transcriptions)


print("Starting transcription...\n")
transcription = transcribe_with_chunking(audio_array, chunk_length_seconds=20)

print("\n" + "="*60)
print("TRANSCRIPTION (Egyptian Arabic / arz):")
print("="*60)
print(transcription)
print("="*60)

"""## ⏱️ Step 7 — Word-Level Alignment with WhisperX

WhisperX aligns the transcription to the audio giving exact timestamps per word.

"""

import whisperx

# Use WhisperX for alignment only; transcription comes from Step 6 (e.g. Seamless M4T).
print("WhisperX will be used for word-level alignment only (no Whisper transcription).")


def align_with_whisperx(audio_array, transcript_text, sample_rate=16000):
    """Align existing transcript to audio; return list of dicts with keys: word, start, end, duration."""
    temp_audio = "/content/temp_align.wav"
    sf.write(temp_audio, audio_array, sample_rate)
    audio = whisperx.load_audio(temp_audio)
    duration_sec = len(audio_array) / sample_rate

    # Build one segment from your transcript (full audio span)
    segments = [{"text": transcript_text.strip(), "start": 0.0, "end": duration_sec}]

    print("Step 1: Word-level alignment (using your transcript)...")
    try:
        model_a, metadata = whisperx.load_align_model(language_code="ar", device=device)
        result_aligned = whisperx.align(
            segments, model_a, metadata,
            audio, device, return_char_alignments=False,
        )
        del model_a
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        print("  Word-level alignment done.")
    except Exception as e:
        print(f"  Alignment failed ({e}), falling back to even segment split.")
        # Fallback: no word-level times, spread words evenly
        result_aligned = {"segments": [{"text": transcript_text.strip(), "start": 0.0, "end": duration_sec, "words": None}]}

    # Extract words
    word_timestamps = []
    for seg in result_aligned["segments"]:
        if "words" in seg and seg["words"]:
            for w in seg["words"]:
                if w.get("word", "").strip() and "start" in w and "end" in w:
                    word_timestamps.append({
                        "word"    : w["word"].strip(),
                        "start"   : round(w["start"], 3),
                        "end"     : round(w["end"],   3),
                        "duration": round(w["end"] - w["start"], 3),
                    })
        else:
            words = seg["text"].strip().split()
            dur   = seg["end"] - seg["start"]
            wdur  = dur / max(len(words), 1)
            for k, word in enumerate(words):
                s = seg["start"] + k * wdur
                word_timestamps.append({
                    "word"    : word,
                    "start"   : round(s,        3),
                    "end"     : round(s + wdur, 3),
                    "duration": round(wdur,      3),
                })

    os.remove(temp_audio)
    return word_timestamps


print("\nAligning audio (using transcript from Step 6)...")
aligned_segments = align_with_whisperx(audio_array, transcription)

print(f"\n{len(aligned_segments)} words with timestamps")
print("\nFirst 20 words:")
for i, seg in enumerate(aligned_segments[:20], 1):
    print(f"  {i:3}. [{seg['start']:7.3f}s - {seg['end']:7.3f}s]  {seg['word']}")
if len(aligned_segments) > 20:
    print(f"  ... and {len(aligned_segments)-20} more")

import pandas as pd
from IPython.display import display, HTML

# Build DataFrame
df = pd.DataFrame(aligned_segments)
df.index = df.index + 1  # 1-based index
df["duration"] = df["duration"].map(lambda x: f"{x:.3f}s")
df["start"]    = df["start"].map(lambda x: f"{x:.3f}s")
df["end"]      = df["end"].map(lambda x: f"{x:.3f}s")
df.columns     = ["Word", "Start", "End", "Duration"]

styled = (
    df.style
      .set_caption(f"✅ {len(df)} aligned words")
      .set_table_styles([
          {"selector": "caption",
           "props": [("font-size", "16px"), ("font-weight", "bold"),
                     ("padding-bottom", "8px"), ("color", "#2d6a4f")]},
          {"selector": "thead th",
           "props": [("background-color", "#2d6a4f"), ("color", "white"),
                     ("font-size", "13px"), ("padding", "8px 12px"),
                     ("text-align", "center")]},
          {"selector": "tbody td",
           "props": [("padding", "6px 12px"), ("font-size", "13px"),
                     ("text-align", "center"), ("border-bottom", "1px solid #e0e0e0")]},
          {"selector": "tbody tr:nth-child(even)",
           "props": [("background-color", "#f5f5f5")]},
          {"selector": "tbody tr:hover",
           "props": [("background-color", "#d8f3dc")]},
      ])
      .set_properties(subset=["Word"],
                      **{"font-weight": "bold", "color": "#1b4332",
                         "text-align": "right", "direction": "rtl"})  # RTL for Arabic
)

display(styled)

"""## 📜 Step 8 — Upload Your Original Script





"""

print("Upload your original script file (.txt / .json / .srt):")
uploaded_script = files.upload()
SCRIPT_FILE = list(uploaded_script.keys())[0]
print(f"✅ Script uploaded: {SCRIPT_FILE}")

"""## 📊 Step 9 — Compare Script vs Transcript"""

# == Arabic normalisation (enhanced) ==========================================

# Arabic-Indic -> Western digit map
_ARABIC_INDIC_DIGITS = str.maketrans("\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669",
                                      "0123456789")

def normalize_arabic(text):
    # 0. Strip zero-width & invisible characters (ZWS, ZWNJ, ZWJ, BOM)
    text = re.sub(r"[\u200B\u200C\u200D\uFEFF]", "", text)

    # 1. Tatweel (kashida) removal
    text = text.replace("\u0640", "")  # tatweel character

    # 2. Lam-Alef ligatures -> plain lam + alef
    text = re.sub(r"[\uFEF5\uFEF6\uFEF7\uFEF8]", "\u0644\u0627", text)
    text = re.sub("\u0644\u0623|\u0644\u0625|\u0644\u0622|\u0644\u0627", "\u0644\u0627", text)

    # 3. Diacritics removal (tashkeel + shadda U+0651 is inside this range)
    text = re.sub(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06DC\u06DF-\u06E4\u06E7\u06E8\u06EA-\u06ED]", "", text)

    # 4. Hamza / Alef normalization
    text = re.sub("[\u0625\u0623\u0622\u0627\u0671]", "\u0627", text)   # all alef variants -> bare alef
    text = re.sub("[\u0624\u0676]",    "\u0648", text)   # hamza on waw + variant -> waw
    text = re.sub("[\u0626]",           "\u064A", text)   # hamza on ya -> ya
    text = re.sub("[\u0621\u0655\u0654]", "\u0627", text)  # standalone hamza -> alef

    # 5. Other letter normalizations
    text = re.sub("\u0649",  "\u064A", text)   # alef maqsura -> ya
    text = re.sub("\u0629",  "\u0647", text)   # ta marbuta -> ha
    text = re.sub("\u06AF", "\u0643", text)   # Persian kaf -> Arabic kaf

    # 6. Arabic-Indic digit -> Western digit
    text = text.translate(_ARABIC_INDIC_DIGITS)

    # 7. Repeated character collapsing (e.g. kbyyyr -> kbyr)
    text = re.sub(r"(.)\1{2,}", r"\1\1", text)
    text = re.sub(r"(.)\1+",   r"\1",    text)

    # 8. Punctuation & whitespace cleanup
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+",      " ", text)
    return text.strip()


# == Damerau-Levenshtein distance (capped at 2 for speed) =====================
def _dam_lev(a, b, cap=2):
    la, lb = len(a), len(b)
    if abs(la - lb) > cap:
        return cap + 1
    if a == b:
        return 0
    prev2 = list(range(lb + 1))
    prev1 = [0] * (lb + 1)
    for i in range(1, la + 1):
        curr = [i] + [0] * lb
        for j in range(1, lb + 1):
            cost = 0 if a[i-1] == b[j-1] else 1
            curr[j] = min(curr[j-1] + 1,
                          prev1[j]   + 1,
                          prev1[j-1] + cost)
            # transposition of adjacent letters
            if i > 1 and j > 1 and a[i-1] == b[j-2] and a[i-2] == b[j-1]:
                curr[j] = min(curr[j], prev2[j-2] + cost)
        prev2, prev1 = prev1, curr
    return prev1[lb]

def words_are_close(w1, w2):
    """True if words differ by at most 2 edits (including adjacent transposition).
    Single-character words must match exactly to avoid over-matching particles.
    """
    if not w1 or not w2:
        return False
    # Only block exact-match for single-char words (like و, ف, ب)
    if min(len(w1), len(w2)) == 1:
        return w1 == w2
    return _dam_lev(w1, w2, cap=2) <= 2


# == Egyptian Arabic number words -> digits ====================================
_NUM_WORDS = {
    'واحد':'1','وحده':'1','وحدها':'1','وحدهم':'1',
    'اتنين':'2','اثنين':'2','تنين':'2','اثنتين':'2',
    'تلاتة':'3','تلاته':'3','ثلاثة':'3','تلات':'3','ثلاث':'3',
    'اربعة':'4','اربعه':'4','اربع':'4',
    'خمسة':'5','خمسه':'5','خمس':'5',
    'ستة':'6','سته':'6','ست':'6',
    'سبعة':'7','سبعه':'7','سبع':'7',
    'تمانية':'8','تمانيه':'8','ثمانية':'8','تمان':'8','تمنية':'8',
    'تسعة':'9','تسعه':'9','تسع':'9',
    'عشرة':'10','عشره':'10','عشر':'10',
    'عشرين':'20','تلاتين':'30','ثلاثين':'30',
    'اربعين':'40','خمسين':'50','ستين':'60',
    'سبعين':'70','تمانين':'80','تسعين':'90',
    'مية':'100','ميه':'100','مئة':'100','مائة':'100',
    'الف':'1000','الاف':'1000',
}

# == Sequence-level normalisation: contractions + number words =================
def normalize_word_sequence(words):
    """
    Scans a token list and applies two operations:
    1. Egyptian negation contractions (pattern-based, not a fixed table):
           ما + verb     ->  م + verb       (e.g. ما فيش  -> مفيش)
           ما + pronoun  ->  ما + pronoun    (e.g. ما هو   -> ماهو)
           مش + word     ->  مش + word       (e.g. مش عارف -> مشعارف)
           على + شان     ->  علشان
    2. Number words -> digits (e.g. تلاتة -> 3)
    """
    _PRONOUNS = {'هو','هي','هم','هما','انت','انتي','انتو','احنا','انا','ده','دي','دول'}
    result = []
    i = 0
    while i < len(words):
        w = words[i]
        if w == 'ما' and i + 1 < len(words):
            nxt = words[i + 1]
            result.append('ما' + nxt if nxt in _PRONOUNS else 'م' + nxt)
            i += 2; continue
        if w == 'مش' and i + 1 < len(words):
            result.append('مش' + words[i + 1])
            i += 2; continue
        if w == 'على' and i + 1 < len(words) and words[i + 1] == 'شان':
            result.append('علشان')
            i += 2; continue
        result.append(_NUM_WORDS.get(w, w))
        i += 1
    return result


# == SRT helpers ===============================================================
def srt_to_seconds(ts):
    ts = ts.replace(",", ".")
    h, m, s = ts.split(":")
    return int(h)*3600 + int(m)*60 + float(s)

def parse_srt(content):
    segs, lines, i = [], content.strip().split("\n"), 0
    while i < len(lines):
        if lines[i].strip().isdigit():
            i += 1
        if i < len(lines) and "-->" in lines[i]:
            parts = lines[i].split("-->")
            s, e  = srt_to_seconds(parts[0].strip()), srt_to_seconds(parts[1].strip().split()[0])
            i += 1
            texts = []
            while i < len(lines) and lines[i].strip() and not lines[i].strip().isdigit():
                texts.append(lines[i].strip()); i += 1
            if texts:
                segs.append({"text": " ".join(texts), "start": s, "end": e})
        i += 1
    return segs

def load_script(path):
    with open(path, encoding="utf-8") as f:
        content = f.read()
    if path.endswith(".json"):
        data = json.loads(content)
        if isinstance(data, list) and data and "start" in data[0]:
            return data
        return [{"text": data.get("text", content), "start": 0, "end": 0}]
    if path.endswith(".srt"):
        return parse_srt(content)
    return [{"text": content, "start": 0, "end": 0}]


# == Load & normalize ==========================================================
script_segments = load_script(SCRIPT_FILE)
# NEW — strip emotion labels in quotes before building norm_script
import re
def strip_emotion_labels(text):
    return re.sub(r'"[^"]+"', '', text)

script_text = " ".join(strip_emotion_labels(seg["text"].strip()) for seg in script_segments)
norm_script     = normalize_arabic(script_text)
norm_transcript = " ".join(normalize_arabic(seg["word"]) for seg in aligned_segments)

print(f"Script    : {len(norm_script.split())} words")
print(f"Transcript: {len(norm_transcript.split())} words")


# == Word-level comparison =====================================================
def compare(norm_script, norm_transcript, aligned_segments):
    sw = normalize_word_sequence(norm_script.split())
    tw = normalize_word_sequence(norm_transcript.split())

    ts_list = [{"word": normalize_arabic(s["word"]), "start": s["start"], "end": s["end"]}
               for s in aligned_segments]

    rows, t_idx = [], 0
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, sw, tw).get_opcodes():
        if tag == "equal":
            for k in range(i2 - i1):
                ts = ts_list[t_idx]["start"] if t_idx < len(ts_list) else None
                rows.append({"Status": "\u2713 Match", "Script": sw[i1+k], "Transcript": tw[j1+k],
                              "Timestamp": f"{ts:.2f}s" if ts is not None else "N/A", "Note": ""})
                t_idx += 1
        elif tag == "replace":
            # -- General merged-word check (any 2 tokens -> 1 or 1 -> 2) --
            _handled = False
            if (i2-i1) == 1 and (j2-j1) == 2:
                merged_t = tw[j1] + tw[j1+1]
                if sw[i1] == merged_t or words_are_close(sw[i1], merged_t):
                    ts = ts_list[t_idx]["start"] if t_idx < len(ts_list) else None
                    rows.append({"Status": "\u2713 Match", "Script": sw[i1],
                                 "Transcript": merged_t,
                                 "Timestamp": f"{ts:.2f}s" if ts is not None else "N/A",
                                 "Note": f"merged: {tw[j1]!r}+{tw[j1+1]!r}"})
                    t_idx += 2; _handled = True
            elif (i2-i1) == 2 and (j2-j1) == 1:
                merged_s = sw[i1] + sw[i1+1]
                if merged_s == tw[j1] or words_are_close(merged_s, tw[j1]):
                    ts = ts_list[t_idx]["start"] if t_idx < len(ts_list) else None
                    rows.append({"Status": "\u2713 Match", "Script": merged_s,
                                 "Transcript": tw[j1],
                                 "Timestamp": f"{ts:.2f}s" if ts is not None else "N/A",
                                 "Note": f"split: {sw[i1]!r}+{sw[i1+1]!r}"})
                    t_idx += 1; _handled = True
            if not _handled:
              for k in range(max(i2-i1, j2-j1)):
                s_w = sw[i1+k] if i1+k < i2 else ""
                t_w = tw[j1+k] if j1+k < j2 else ""
                ts  = ts_list[t_idx]["start"] if t_w and t_idx < len(ts_list) else None
                if s_w and t_w:
                    if words_are_close(s_w, t_w):
                        status = "\u2713 Match"
                        note   = f"~1-edit: {s_w!r} ~ {t_w!r}"
                    else:
                        status = "\U0001f7e1 Changed"
                        note   = f"{s_w!r} -> {t_w!r}"
                elif s_w:
                    status, note, ts = "\U0001f534 Skipped", f"{s_w!r} not said", None
                else:
                    status, note = "\U0001f7e2 Added", f"{t_w!r} added"
                rows.append({"Status": status, "Script": s_w or "-", "Transcript": t_w or "-",
                              "Timestamp": f"{ts:.2f}s" if ts is not None else "N/A", "Note": note})
                if t_w:
                    t_idx += 1
        elif tag == "delete":
            for k in range(i2-i1):
                rows.append({"Status": "\U0001f534 Skipped", "Script": sw[i1+k], "Transcript": "-",
                              "Timestamp": "N/A", "Note": f"{sw[i1+k]!r} not said"})
        elif tag == "insert":
            for k in range(j2-j1):
                ts = ts_list[t_idx]["start"] if t_idx < len(ts_list) else None
                rows.append({"Status": "\U0001f7e2 Added", "Script": "-", "Transcript": tw[j1+k],
                              "Timestamp": f"{ts:.2f}s" if ts is not None else "N/A",
                              "Note": f"{tw[j1+k]!r} added"})
                t_idx += 1
    return pd.DataFrame(rows)

df = compare(norm_script, norm_transcript, aligned_segments)

# == Summary ===================================================================
total   = len(df)
matched = (df["Status"] == "\u2713 Match").sum()
changed = (df["Status"] == "\U0001f7e1 Changed").sum()
skipped = (df["Status"] == "\U0001f534 Skipped").sum()
added   = (df["Status"] == "\U0001f7e2 Added").sum()

print("\n" + "="*60)
print("Summary")
print("="*60)
print(f"Total     : {total}")
print(f"Match     : {matched}  ({matched/total*100:.1f}%)")
print(f"Changed   : {changed}  ({changed/total*100:.1f}%)")
print(f"Skipped   : {skipped}  ({skipped/total*100:.1f}%)")
print(f"Added     : {added}    ({added/total*100:.1f}%)")
accuracy = matched / max(matched + changed + skipped, 1) * 100
print(f"\nWord Accuracy: {accuracy:.1f}%")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", 60)
print("\nFull Comparison Table:")
display(df)
# == Display only Skipped / Added / Changed rows ==============================

FILTER_STATUSES = {"🟡 Changed", "🔴 Skipped", "🟢 Added"}

df_issues = df[df["Status"].isin(FILTER_STATUSES)].reset_index(drop=True)

# == Summary ===================================================================
print("\n" + "="*60)
print("Issues Only (Skipped / Added / Changed)")
print("="*60)
print(f"Changed : {(df_issues['Status'] == '🟡 Changed').sum()}")
print(f"Skipped : {(df_issues['Status'] == '🔴 Skipped').sum()}")
print(f"Added   : {(df_issues['Status'] == '🟢 Added').sum()}")
print(f"Total   : {len(df_issues)}")

# == Display ===================================================================
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", 60)
print("\nFiltered Comparison Table:")
display(df_issues)

import re

def parse_script_to_json(filepath):
    """Parse txt where each sentence ends with "EmotionLabel" in double quotes."""
    with open(filepath, encoding='utf-8') as f:
        raw = f.read()
    raw = re.sub(r'[\r\n]+', ' ', raw)
    raw = re.sub(r'\s+', ' ', raw).strip()
    sentences = []
    for content, emotion in re.findall(r'(.*?)"([^"]+)"', raw):
        content = content.strip()
        if content:
            sentences.append({'content': content, 'emotion': emotion.strip().lower()})
    return sentences

SCRIPT_PATH = SCRIPT_FILE
sentences   = parse_script_to_json(SCRIPT_PATH)

print(f"✅ {len(sentences)} sentences loaded:")
for i, s in enumerate(sentences):
    print(f"  [{i+1}] {s['emotion'].upper():10s} | {s['content'][:60]}")

import json

def build_word_sent_map(sentences):
    """Map each script word index → sentence index."""
    mapping = []
    for s_idx, entry in enumerate(sentences):
        # reuse your existing normalize_arabic function
        words = normalize_arabic(entry['content']).split()
        for _ in words:
            mapping.append(s_idx)
    return mapping

def annotate_sent_idx(df, script_word_to_sent):
    """Tag each row in comparison df with its sentence index."""
    cursor, last, indices = 0, 0, []
    for _, row in df.iterrows():
        if row['Script'] != '-':           # real script word
            if cursor < len(script_word_to_sent):
                last = script_word_to_sent[cursor]
                cursor += 1
        indices.append(last)               # added words inherit last sentence
    df = df.copy()
    df['sent_idx'] = indices
    return df

def reconstruct_timestamps(df_annotated, sentences, total_duration):
    """Build sentence-level timestamps from the comparison table."""
    def to_float(ts):
        try: return float(str(ts).replace('s', '').strip())
        except: return None

    df_annotated = df_annotated.copy()
    df_annotated['_t'] = df_annotated['Timestamp'].apply(to_float)
    USABLE = {'✓ Match', '🟡 Changed', '🟢 Added'}
    enriched = []

    for s_idx, entry in enumerate(sentences):
        sdf    = df_annotated[df_annotated['sent_idx'] == s_idx]
        usable = sdf[sdf['_t'].notna() & sdf['Status'].isin(USABLE)]

        n_script = max(len(sdf[sdf['Script'] != '-']), 1)
        n_said   = len(sdf[sdf['Status'].isin({'✓ Match', '🟡 Changed'})])
        coverage = n_said / n_script

        if len(usable) == 0:
            enriched.append({
                'content' : entry['content'],
                'emotion' : entry['emotion'],
                't_start' : None,
                't_end'   : None,
                'coverage': 0.0,
                'status'  : 'missing'
            })
            continue

        t_start  = usable['_t'].min()
        next_sdf = df_annotated[df_annotated['sent_idx'] == s_idx + 1]
        next_t   = next_sdf[next_sdf['_t'].notna()]

        if len(next_t) > 0:
            t_end = (usable['_t'].max() + next_t['_t'].min()) / 2.0
        else:
            t_end = total_duration

        t_start = max(0.0, t_start)
        t_end   = min(total_duration, t_end)
        if t_end <= t_start:
            t_end = min(t_start + 0.5, total_duration)

        enriched.append({
            'content' : entry['content'],
            'emotion' : entry['emotion'],
            't_start' : round(t_start, 4),
            't_end'   : round(t_end,   4),
            'coverage': round(coverage, 3),
            'status'  : 'ok' if coverage >= 0.5 else 'partial'
        })

    return enriched

# ── Run ───────────────────────────────────────────────────────────────────────
# total_duration: replace with however you get audio length in your notebook
# e.g. total_duration = len(audio_array) / sr   OR   waveform.shape[1] / sr
total_duration = max(seg['end'] for seg in aligned_segments)

script_word_to_sent = build_word_sent_map(sentences)
df_annotated        = annotate_sent_idx(df, script_word_to_sent)
sentences_aligned   = reconstruct_timestamps(df_annotated, sentences, total_duration)

# ── Print summary ─────────────────────────────────────────────────────────────
for i, s in enumerate(sentences_aligned):
    icon = {'ok': '✅', 'partial': '🟡', 'missing': '🔴'}.get(s['status'], '❓')
    t    = f"{s['t_start']:.2f}s → {s['t_end']:.2f}s" if s['t_start'] else 'MISSING'
    print(f"[{i+1:2}] {icon} {s['emotion'].upper():10s} | {t} | cov={s['coverage']*100:.0f}% | {s['content'][:45]}")

# ── Save JSON — load this in the Audio Model notebook ────────────────────────
OUTPUT_PATH = '/content/sentences_aligned.json'
with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    json.dump(sentences_aligned, f, ensure_ascii=False, indent=2)

print(f"\n✅ Saved to: {OUTPUT_PATH}")
print(f"   Copy this file to your Audio Model notebook's input dataset")

# Export df alongside sentences_aligned
df.to_json('/content/comparison_df.json', orient='records', force_ascii=False)

with open('/content/sentences_aligned.json', 'w', encoding='utf-8') as f:
    json.dump(sentences_aligned, f, ensure_ascii=False, indent=2)

print("✅ Saved comparison_df.json")
print("✅ Saved sentences_aligned.json")

# ── Download both files ───────────────────────────────────────────────────────
from google.colab import files
files.download('/content/comparison_df.json')
files.download('/content/sentences_aligned.json')